### ISSUE TITLE
Consider inserting many database rows in a single query

### ISSUE THREAD

**Issue by toolness** [aepyornis/nyc-db#42]
While working on #41, I noticed that the `Database.insert_rows()` method executes an individual `SQL INSERT` statement for each row in a data set.

I'm not a database expert by any means, but Django has a [`bulk_create`](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#bulk-create) method that inserts multiple records in a single query, which I've found increases efficiency quite a bit, at least in Django-land.  So I'm curious if this could potentially speed up dataset loading in nycdb too.

**Comment by aepyornis** [comment]
` Database.insert_rows() ` already executes the INSERT statements inside a single transaction, which saves a lot of overhead. I've not used Django, but I image that a lot of the cost of doing single create vs bulk create is the cost of separate transactions and of updating the indexes.  In NYCDB, the batch size is set to 1,000, meaning 1,000 inserts per transaction. 

However,  postgres does support  a multirow  syntax: 
``` sql
INSERT INTO hpd_violations VALUES 
 ( col1, col2, ...),
 ( col1, col2, ...),
 ( col1, col2, ...)
);
```

My hunch is that it's not going to save use that much time since we generally don't index the columns until later and therefore there are no indexes to update, but we should perf test it and see -- maybe it does speed it up!
