### ISSUE TITLE
Dockerfile no longer uses minimum supported version of Python?

### ISSUE THREAD

**Issue by toolness** [aepyornis/nyc-db#61]
Hi!  I noticed that in 4512e6be162f47c227ddaf52278be5f3f2be8d4f the Python version used by the Dockerfile got changed to 3.6, but the reason it was 3.5 was so that, by forcing Docker to use the minimum-supported version of Python that NYCDB supports, we wouldn't accidentally use 3.6 features that broke folks on 3.5...

Or are we dropping 3.5 support from NYCDB?  Anyways, just thought I'd flag it.

**Comment by aepyornis** [comment]
Travis will run our tests in 3.5, 3.6, and 3.7, so as long as we write complete tests we'll catch any features that are not compatible. 

Supporting python 3.5 seems useful because it's installed by default in Debian stable (but I might be the only one who cares about that, so i'm open to dropping it if there's features in python 3.6/3.7 that are useful). I'm not a huge python user, so I haven't been keeping up with the new features...

**Comment by toolness** [comment]
Oh ok--I just found it useful to have my dev environment (i.e. docker) be the lowest-common-denominator so that I could easily find/debug/fix 3.5 problems without having to wait for travis to tell me everything is OK, but it's up to you.

That said, I am a huge fan of [Python 3.6's f-strings](https://realpython.com/python-f-strings/) and they're what I miss most when I have to code for 3.5, so I'm looking forward to it reaching end-of-life, hehe.

**Comment by aepyornis** [comment]
I'm totally cool with dropping support for python 3.5 if using f-strings is helpful for you.

**Comment by toolness** [comment]
Ok cool thanks, good to know!

**Comment by toolness** [comment]
I guess I will close this for now since there's no further action to be taken.
